// <auto-generated />
using System;
using CarZone.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarZone.Infrastructure.Migrations
{
    [DbContext(typeof(CarZoneDBContext))]
    [Migration("20260204164603_user_roles_added")]
    partial class user_roles_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarZone.Domain.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "BMW"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Audi"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Mercedes-Benz"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Volkswagen"
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Toyota"
                        },
                        new
                        {
                            BrandId = 6,
                            BrandName = "Honda"
                        },
                        new
                        {
                            BrandId = 7,
                            BrandName = "Ford"
                        },
                        new
                        {
                            BrandId = 8,
                            BrandName = "Opel"
                        },
                        new
                        {
                            BrandId = 9,
                            BrandName = "Peugeot"
                        },
                        new
                        {
                            BrandId = 10,
                            BrandName = "Renault"
                        },
                        new
                        {
                            BrandId = 11,
                            BrandName = "Skoda"
                        },
                        new
                        {
                            BrandId = 12,
                            BrandName = "Hyundai"
                        },
                        new
                        {
                            BrandId = 13,
                            BrandName = "Kia"
                        },
                        new
                        {
                            BrandId = 14,
                            BrandName = "Mazda"
                        },
                        new
                        {
                            BrandId = 15,
                            BrandName = "Nissan"
                        },
                        new
                        {
                            BrandId = 16,
                            BrandName = "Volvo"
                        },
                        new
                        {
                            BrandId = 17,
                            BrandName = "Fiat"
                        },
                        new
                        {
                            BrandId = 18,
                            BrandName = "Alfa Romeo"
                        },
                        new
                        {
                            BrandId = 19,
                            BrandName = "Porsche"
                        },
                        new
                        {
                            BrandId = 20,
                            BrandName = "Tesla"
                        },
                        new
                        {
                            BrandId = 21,
                            BrandName = "Ferrari"
                        },
                        new
                        {
                            BrandId = 22,
                            BrandName = "Lamborghini"
                        },
                        new
                        {
                            BrandId = 23,
                            BrandName = "Maserati"
                        },
                        new
                        {
                            BrandId = 24,
                            BrandName = "Bentley"
                        },
                        new
                        {
                            BrandId = 25,
                            BrandName = "Rolls-Royce"
                        });
                });

            modelBuilder.Entity("CarZone.Domain.Models.Listing", b =>
                {
                    b.Property<int>("ListingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingID"));

                    b.Property<string>("AdditionalDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BodyType")
                        .HasColumnType("int");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int");

                    b.Property<int>("EngineType")
                        .HasColumnType("int");

                    b.Property<double>("FuelConsuption")
                        .HasColumnType("float");

                    b.Property<int>("ListingStatus")
                        .HasColumnType("int");

                    b.Property<double>("Mileage")
                        .HasColumnType("float");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PublishedDate")
                        .HasColumnType("date");

                    b.Property<int>("Transmission")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ListingID");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId");

                    b.ToTable("Listing");
                });

            modelBuilder.Entity("CarZone.Domain.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModelId");

                    b.HasIndex("BrandId");

                    b.ToTable("Model");

                    b.HasData(
                        new
                        {
                            ModelId = 1,
                            BrandId = 1,
                            ModelName = "Series 3"
                        },
                        new
                        {
                            ModelId = 2,
                            BrandId = 1,
                            ModelName = "Series 5"
                        },
                        new
                        {
                            ModelId = 3,
                            BrandId = 1,
                            ModelName = "X5"
                        },
                        new
                        {
                            ModelId = 4,
                            BrandId = 2,
                            ModelName = "A4"
                        },
                        new
                        {
                            ModelId = 5,
                            BrandId = 2,
                            ModelName = "A6"
                        },
                        new
                        {
                            ModelId = 6,
                            BrandId = 2,
                            ModelName = "Q7"
                        },
                        new
                        {
                            ModelId = 7,
                            BrandId = 3,
                            ModelName = "C-Class"
                        },
                        new
                        {
                            ModelId = 8,
                            BrandId = 3,
                            ModelName = "E-Class"
                        },
                        new
                        {
                            ModelId = 9,
                            BrandId = 3,
                            ModelName = "GLE"
                        },
                        new
                        {
                            ModelId = 10,
                            BrandId = 4,
                            ModelName = "Golf"
                        },
                        new
                        {
                            ModelId = 11,
                            BrandId = 4,
                            ModelName = "Passat"
                        },
                        new
                        {
                            ModelId = 12,
                            BrandId = 4,
                            ModelName = "Tiguan"
                        },
                        new
                        {
                            ModelId = 13,
                            BrandId = 5,
                            ModelName = "Corolla"
                        },
                        new
                        {
                            ModelId = 14,
                            BrandId = 5,
                            ModelName = "Camry"
                        },
                        new
                        {
                            ModelId = 15,
                            BrandId = 5,
                            ModelName = "RAV4"
                        },
                        new
                        {
                            ModelId = 16,
                            BrandId = 6,
                            ModelName = "Civic"
                        },
                        new
                        {
                            ModelId = 17,
                            BrandId = 6,
                            ModelName = "Accord"
                        },
                        new
                        {
                            ModelId = 18,
                            BrandId = 6,
                            ModelName = "CR-V"
                        },
                        new
                        {
                            ModelId = 19,
                            BrandId = 7,
                            ModelName = "Focus"
                        },
                        new
                        {
                            ModelId = 20,
                            BrandId = 7,
                            ModelName = "Mondeo"
                        },
                        new
                        {
                            ModelId = 21,
                            BrandId = 7,
                            ModelName = "Mustang"
                        },
                        new
                        {
                            ModelId = 22,
                            BrandId = 8,
                            ModelName = "Astra"
                        },
                        new
                        {
                            ModelId = 23,
                            BrandId = 8,
                            ModelName = "Insignia"
                        },
                        new
                        {
                            ModelId = 24,
                            BrandId = 8,
                            ModelName = "Corsa"
                        },
                        new
                        {
                            ModelId = 25,
                            BrandId = 9,
                            ModelName = "208"
                        },
                        new
                        {
                            ModelId = 26,
                            BrandId = 9,
                            ModelName = "308"
                        },
                        new
                        {
                            ModelId = 27,
                            BrandId = 9,
                            ModelName = "3008"
                        },
                        new
                        {
                            ModelId = 28,
                            BrandId = 10,
                            ModelName = "Clio"
                        },
                        new
                        {
                            ModelId = 29,
                            BrandId = 10,
                            ModelName = "Megane"
                        },
                        new
                        {
                            ModelId = 30,
                            BrandId = 10,
                            ModelName = "Kadjar"
                        },
                        new
                        {
                            ModelId = 31,
                            BrandId = 11,
                            ModelName = "Octavia"
                        },
                        new
                        {
                            ModelId = 32,
                            BrandId = 11,
                            ModelName = "Superb"
                        },
                        new
                        {
                            ModelId = 33,
                            BrandId = 11,
                            ModelName = "Kodiaq"
                        },
                        new
                        {
                            ModelId = 34,
                            BrandId = 12,
                            ModelName = "i30"
                        },
                        new
                        {
                            ModelId = 35,
                            BrandId = 12,
                            ModelName = "Tucson"
                        },
                        new
                        {
                            ModelId = 36,
                            BrandId = 12,
                            ModelName = "Santa Fe"
                        },
                        new
                        {
                            ModelId = 37,
                            BrandId = 13,
                            ModelName = "Ceed"
                        },
                        new
                        {
                            ModelId = 38,
                            BrandId = 13,
                            ModelName = "Sportage"
                        },
                        new
                        {
                            ModelId = 39,
                            BrandId = 13,
                            ModelName = "Sorento"
                        },
                        new
                        {
                            ModelId = 40,
                            BrandId = 14,
                            ModelName = "Mazda 3"
                        },
                        new
                        {
                            ModelId = 41,
                            BrandId = 14,
                            ModelName = "Mazda 6"
                        },
                        new
                        {
                            ModelId = 42,
                            BrandId = 14,
                            ModelName = "CX-5"
                        },
                        new
                        {
                            ModelId = 43,
                            BrandId = 15,
                            ModelName = "Qashqai"
                        },
                        new
                        {
                            ModelId = 44,
                            BrandId = 15,
                            ModelName = "X-Trail"
                        },
                        new
                        {
                            ModelId = 45,
                            BrandId = 15,
                            ModelName = "Micra"
                        },
                        new
                        {
                            ModelId = 46,
                            BrandId = 16,
                            ModelName = "S60"
                        },
                        new
                        {
                            ModelId = 47,
                            BrandId = 16,
                            ModelName = "XC60"
                        },
                        new
                        {
                            ModelId = 48,
                            BrandId = 16,
                            ModelName = "XC90"
                        },
                        new
                        {
                            ModelId = 49,
                            BrandId = 17,
                            ModelName = "Punto"
                        },
                        new
                        {
                            ModelId = 50,
                            BrandId = 17,
                            ModelName = "500"
                        },
                        new
                        {
                            ModelId = 51,
                            BrandId = 17,
                            ModelName = "Tipo"
                        },
                        new
                        {
                            ModelId = 52,
                            BrandId = 18,
                            ModelName = "Giulia"
                        },
                        new
                        {
                            ModelId = 53,
                            BrandId = 18,
                            ModelName = "Stelvio"
                        },
                        new
                        {
                            ModelId = 54,
                            BrandId = 19,
                            ModelName = "911"
                        },
                        new
                        {
                            ModelId = 55,
                            BrandId = 19,
                            ModelName = "Cayenne"
                        },
                        new
                        {
                            ModelId = 56,
                            BrandId = 20,
                            ModelName = "Model S"
                        },
                        new
                        {
                            ModelId = 57,
                            BrandId = 20,
                            ModelName = "Model 3"
                        },
                        new
                        {
                            ModelId = 58,
                            BrandId = 20,
                            ModelName = "Model Y"
                        },
                        new
                        {
                            ModelId = 59,
                            BrandId = 21,
                            ModelName = "F8 Tributo"
                        },
                        new
                        {
                            ModelId = 60,
                            BrandId = 21,
                            ModelName = "Roma"
                        },
                        new
                        {
                            ModelId = 61,
                            BrandId = 22,
                            ModelName = "Huracan"
                        },
                        new
                        {
                            ModelId = 62,
                            BrandId = 22,
                            ModelName = "Aventador"
                        },
                        new
                        {
                            ModelId = 63,
                            BrandId = 23,
                            ModelName = "Ghibli"
                        },
                        new
                        {
                            ModelId = 64,
                            BrandId = 23,
                            ModelName = "Levante"
                        },
                        new
                        {
                            ModelId = 65,
                            BrandId = 24,
                            ModelName = "Continental GT"
                        },
                        new
                        {
                            ModelId = 66,
                            BrandId = 24,
                            ModelName = "Bentayga"
                        },
                        new
                        {
                            ModelId = 67,
                            BrandId = 25,
                            ModelName = "Ghost"
                        },
                        new
                        {
                            ModelId = 68,
                            BrandId = 25,
                            ModelName = "Phantom"
                        },
                        new
                        {
                            ModelId = 69,
                            BrandId = 27,
                            ModelName = "Atto 3"
                        },
                        new
                        {
                            ModelId = 70,
                            BrandId = 27,
                            ModelName = "Seal"
                        });
                });

            modelBuilder.Entity("CarZone.Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Milutina Stojanovica 14",
                            Email = "mm@gmail.com",
                            FirstName = "Miljan",
                            HashPassword = "mypassword",
                            LastName = "Mitic",
                            Phone = "0668049057",
                            Roles = "[\"User\"]"
                        });
                });

            modelBuilder.Entity("CarZone.Domain.Models.Listing", b =>
                {
                    b.HasOne("CarZone.Domain.Models.User", "Buyer")
                        .WithMany("BoughtListing")
                        .HasForeignKey("BuyerId");

                    b.HasOne("CarZone.Domain.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarZone.Domain.Models.User", "User")
                        .WithMany("PostedListings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Model");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarZone.Domain.Models.Model", b =>
                {
                    b.HasOne("CarZone.Domain.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CarZone.Domain.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("CarZone.Domain.Models.User", b =>
                {
                    b.Navigation("BoughtListing");

                    b.Navigation("PostedListings");
                });
#pragma warning restore 612, 618
        }
    }
}
