// <auto-generated />
using CarZone.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarZone.Infrastructure.Migrations
{
    [DbContext(typeof(CarZoneDBContext))]
    [Migration("20260122203402_brand_and_model_tables_added")]
    partial class brand_and_model_tables_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarZone.Domain.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "BMW"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Audi"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Mercedes-Benz"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Volkswagen"
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Toyota"
                        },
                        new
                        {
                            BrandId = 6,
                            BrandName = "Honda"
                        },
                        new
                        {
                            BrandId = 7,
                            BrandName = "Ford"
                        },
                        new
                        {
                            BrandId = 8,
                            BrandName = "Opel"
                        },
                        new
                        {
                            BrandId = 9,
                            BrandName = "Peugeot"
                        },
                        new
                        {
                            BrandId = 10,
                            BrandName = "Renault"
                        },
                        new
                        {
                            BrandId = 11,
                            BrandName = "Skoda"
                        },
                        new
                        {
                            BrandId = 12,
                            BrandName = "Hyundai"
                        },
                        new
                        {
                            BrandId = 13,
                            BrandName = "Kia"
                        },
                        new
                        {
                            BrandId = 14,
                            BrandName = "Mazda"
                        },
                        new
                        {
                            BrandId = 15,
                            BrandName = "Nissan"
                        },
                        new
                        {
                            BrandId = 16,
                            BrandName = "Volvo"
                        },
                        new
                        {
                            BrandId = 17,
                            BrandName = "Fiat"
                        },
                        new
                        {
                            BrandId = 18,
                            BrandName = "Alfa Romeo"
                        },
                        new
                        {
                            BrandId = 19,
                            BrandName = "Porsche"
                        },
                        new
                        {
                            BrandId = 20,
                            BrandName = "Tesla"
                        },
                        new
                        {
                            BrandId = 21,
                            BrandName = "Ferrari"
                        },
                        new
                        {
                            BrandId = 22,
                            BrandName = "Lamborghini"
                        },
                        new
                        {
                            BrandId = 23,
                            BrandName = "Maserati"
                        },
                        new
                        {
                            BrandId = 24,
                            BrandName = "Bentley"
                        },
                        new
                        {
                            BrandId = 25,
                            BrandName = "Rolls-Royce"
                        });
                });

            modelBuilder.Entity("CarZone.Domain.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModelId");

                    b.HasIndex("BrandId");

                    b.ToTable("Model");
                });

            modelBuilder.Entity("CarZone.Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Milutina Stojanovica 14",
                            Email = "mm@gmail.com",
                            FirstName = "Miljan",
                            LastName = "Mitic",
                            Password = "mypassword",
                            Phone = "0668049057"
                        });
                });

            modelBuilder.Entity("CarZone.Domain.Models.Model", b =>
                {
                    b.HasOne("CarZone.Domain.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CarZone.Domain.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
